### PR TITLE
Add contribution md file with hacktoberfest rules

### PR DESCRIPTION
**Pull request by atiqueakhtar**
This PR resolves issue #6 with prober contribution rules.

### CODE REVIEW

**Comment by atiqueakhtar** [comment]
Hi @whythoSanskar can you please review the contribution.md file.

**Comment by whythoSanskar** [comment]
@atiqueakhtar Would you reference CodeofConduct.md file as in
- Please follow our [Code of Conduct.md](https://github.com/whythoSanskar/TwitterBot/blob/main/CodeofConduct.md)
and add some more relevant thing like please  look before any actions or similar

**Comment by atiqueakhtar** [comment]
> @atiqueakhtar Would you reference CodeofConduct.md file as in
> 
> * Please follow our [Code of Conduct.md](https://github.com/whythoSanskar/TwitterBot/blob/main/CodeofConduct.md)
>   and add some more relevant thing like please  look before any actions or similar

sure will do

**Comment by atiqueakhtar** [comment]
@whythoSanskar please re-review.

**Review by whythoSanskar — APPROVED** [review]
All the changes are reviewed and are good to merge.

**Pull request merged**
