### PR TITLE
Added CodeofConduct.md file

### PR DESCRIPTION
**Pull request by yash206**

### CODE REVIEW

**Comment by yash206** [comment]
pls review

**Comment by yash206** [comment]
and also add hacktoberfest labels

**Review by whythoSanskar — APPROVED** [review]
All the changes are reviewed and is good to merge

**Comment by yash206** [comment]
@whythoSanskar  if possible please add hacktoberfest label also

**Comment by whythoSanskar** [comment]
> @whythoSanskar  if possible please add hacktoberfest label also

I have already given the hacktoberfest-accepted label to your PR

**Pull request merged**
