### PR TITLE
Create new Lighweight Twitter Bot

### PR DESCRIPTION
**Pull request by ayushete02**
An easy-build and lightweight Twitter bot is written in Python. For this project.

### CODE REVIEW

**Comment by whythoSanskar** [comment]
Ok @ayushete02, Your work is great however when I tested this it was supposed to read from the file and separate the tweets using §§§.  But it didn't work as the tweet printed the whole file. Below is the tweet.


image

**Comment by ayushete02** [comment]
I have update the app you can check it

**Comment by whythoSanskar** [comment]
> I have update the app you can check it

@ayushete02, it would be helpful if you give the screenshot of the test case i.e. you can give here screenshot of the tweets which were tweeted using this PR. As it would also help me to cut down my test cases.

**Comment by ayushete02** [comment]
Screenshot (78)

**Review by whythoSanskar — APPROVED** [review]
All the changes looks good to me also no issues found and is good to merge.

**Pull request merged**
